baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Let's Laugh At"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  TixTreeId = ""


[params.ananke.social.follow]
networks = [
  "facebook",
  "bluesky",
  "linkedin",
  "wikipedia"
]

[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "patrickkollitsch"

[params.ananke.social.bluesky]
username = "kollitsch.dev"

[params.ananke.social.wikipedia]
username = "Hugo_(software)"

[params.ananke.social.networks.wikipedia]
slug = "wikipedia"
label = "Wikipedia"
color = "#0645ad"
profile = "https://en.wikipedia.org/wiki/%s"
icon = "wikipedia-w"
